config/routes.rb
Rails.application.routes.draw do
  
  resources :mountains
  root 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mountain.rb
class Mountain < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  before_action :set_mountain, only: [:show, :edit, :update, :destroy]

  # GET /mountains
  # GET /mountains.json
  def index
    @mountains = Mountain.all
  end

  # GET /mountains/1
  # GET /mountains/1.json
  def show
  end

  # GET /mountains/new
  def new
    @mountain = Mountain.new
  end

  # GET /mountains/1/edit
  def edit
  end

  # POST /mountains
  # POST /mountains.json
  def create
    @mountain = Mountain.new(mountain_params)

    respond_to do |format|
      if @mountain.save
        format.html { redirect_to @mountain, notice: 'Mountain was successfully created.' }
        format.json { render :show, status: :created, location: @mountain }
      else
        format.html { render :new }
        format.json { render json: @mountain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mountains/1
  # PATCH/PUT /mountains/1.json
  def update
    respond_to do |format|
      if @mountain.update(mountain_params)
        format.html { redirect_to @mountain, notice: 'Mountain was successfully updated.' }
        format.json { render :show, status: :ok, location: @mountain }
      else
        format.html { render :edit }
        format.json { render json: @mountain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mountains/1
  # DELETE /mountains/1.json
  def destroy
    @mountain.destroy
    respond_to do |format|
      format.html { redirect_to mountains_url, notice: 'Mountain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mountain
      @mountain = Mountain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mountain_params
      params.require(:mountain).permit(:name, :place, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mountains_helper.rb
module MountainsHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<%= link_to 'Mountain', mountains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazonTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mountains/_form.html.erb
<%= form_with(model: mountain, local: true) do |form| %>
  <% if mountain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mountain.errors.count, "error") %> prohibited this mountain from being saved:</h2>

      <ul>
        <% mountain.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mountains/edit.html.erb
<h1>Editing Mountain</h1>

<%= render 'form', mountain: @mountain %>

<%= link_to 'Show', @mountain %> |
<%= link_to 'Back', mountains_path %>

app/views/mountains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mountains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Place</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mountains.each do |mountain| %>
      <tr>
        <td><%= mountain.name %></td>
        <td><%= mountain.place %></td>
        <td><%= mountain.comment %></td>
        <td><%= link_to 'Show', mountain %></td>
        <td><%= link_to 'Edit', edit_mountain_path(mountain) %></td>
        <td><%= link_to 'Destroy', mountain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mountain', new_mountain_path %>

app/views/mountains/new.html.erb
<h1>New Mountain</h1>

<%= render 'form', mountain: @mountain %>

<%= link_to 'Back', mountains_path %>

app/views/mountains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mountain.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @mountain.place %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @mountain.comment %>
</p>

<%= link_to 'Edit', edit_mountain_path(@mountain) %> |
<%= link_to 'Back', mountains_path %>